### ISSUE TITLE
add option for linking rather than transcluding

### ISSUE THREAD

**Issue by FND** [cdent/purpler#17]
Sometimes `[t <nid>]` is undesirable (perhaps because it's too verbose), so it might be nice to have `[l <nid>]` which only provides the respective URL instead.

Aside: Arguably transcluding should [always include the URL](http://blog.whatfettle.com/2008/10/06/the-uri-is-the-thing/)?

**Comment by cdent** [comment]
> Aside: Arguably transcluding should always include the URL?

It did for a very brief while but then I took it out in fear that people would moan about too much info. I'm happy for it to have the URL.

In fact, if it has the URL, maybe some of the other noise could go away. Not wed to the format, at all.
