### ISSUE TITLE
output of transcluded log message confusing

### ISSUE THREAD

**Issue by cdent** [cdent/purpler#6]
Needs to provide more info but without being noisy.

**Comment by cdent** [comment]
Should it include the url?

**Comment by FND** [comment]
suggestion:

> <FND> go nidclick or something [2016-03-21 16:37:32] [n fU2]

As for the URI, perhaps on a separate line to avoid obscuring the NID?

**Comment by cdent** [comment]
That seems good.

On a busy channel having an additional line would be bad as it could be interleaved with other content, thus losing content.

In perfect universe people would learn they can give the nid to the web app a la http://p.anticdent.org/fU2 and just know the host, but that requires work and we live a lazy universe.
